### ISSUE TITLE
onHover() Panel

### ISSUE THREAD

**Issue by oconorr3** [oconorr3/Maptivity#16]
Eventually we want to be able to display some data in the onHover() panel that is created when a user hovers over a country such as # of data events that have occurred in that geographic region and maybe some graph associated with activity vs. time. The essential idea behind this feature can be view at the following link: http://infosthetics.com/archives/2013/01/tweetping_revealing_worldwide_twitter_activity_in_real_time.html

**Comment by c0d3ster** [comment]
moved this to bottom and map overlays until further notice, closing this.
